.github/workflows/release.yaml
The current CD is just tagging the image `main` instead of a version number.
=> fix: tag version numbers on release images

.github/workflows/release.yaml
The `docker/metadata-action` doesn't handle tags generated inside the workflow, so manually handle the tag instead.
=> fix: manually specify the tag version

cmd/ssh-portal/serve.go, go.mod, internal/sshserver/serve.go
If no host key is defined, a non-persistent host key will be generated
at server start.
=> feat: add ability to configure a persistent host key

internal/serviceapi/sshportal.go, internal/sshserver/authhandler.go
This facilitates tracing and log correlation.
=> feat: send session ID in query to service-api

cmd/service-api/serve.go, internal/serviceapi/server.go
If the NATS server restarts then the connection will close itself due to
authorization failures. Previously the connection closing itself instead
of being instigated by service-api could lead to a deadlock by blocking
on <-ctx.Done().
This change cancels the context in the NATS connection closed handler to
avoid the deadlock.
=> fix: handle NATS connection closing itself

internal/serviceapi/server.go
Occasionally service-api gets into a crashloop with this error
```
service-api: error: couldn't connect to NATS server: nats: Authorization Violation
```
This logging should help to debug this case.
=> chore: add some debug logging for NATS connect errors

.github/workflows/build.yaml, .github/workflows/release.yaml, .github/workflows/tag-to-release.yaml, .goreleaser.yml, README.md, cmd/ssh-portal-api/main.go, cmd/ssh-portal-api/serve.go, cmd/ssh-portal-api/version.go, cmd/ssh-portal/main.go, cmd/ssh-portal/serve.go, cmd/ssh-portal/version.go, deploy/service-api/Dockerfile, deploy/ssh-portal-api/Dockerfile, internal/sshportalapi/server.go, internal/sshportalapi/sshportal.go, internal/sshserver/authhandler.go
This change clarifies the concept of having independent microservices
implementing individual features in Lagoon.
=> feat: rename service-api to ssh-portal-api

cmd/ssh-portal-api/serve.go, internal/sshportalapi/server.go
Significantly simplify some tricky state in the Lagoon charts by not
using user/password authentication for local connections to NATS. The
NATS service is namespace-local and protected by NetworkPolicy, so it is
still protected.
This does not affect authentication and encryption used by Lagoon Remote
NATS leaf clusters connecting to the Lagoon Core NATS cluster. Leaf
cluster connections are still authenticated and encrypted.
=> feat: disable NATS auth for ssh-portal-api

cmd/ssh-portal/serve.go, internal/sshportalapi/server.go
This makes it easier to introspect the NATS connection state from the log.
=> feat: log NATS disconnects

internal/keycloak/client.go
This is a sensitive value and should not be logged.
=> fix: do not log user token value

.github/dependabot.yml
This way we also get Dockerfile auto-updates.
=> chore: add docker to dependabot

internal/sshserver/sessionhandler.go
This matches the behaviour of the Lagoon ssh service.
=> fix: set custom umask in sftp sessions

cmd/ssh-portal/main.go
The spdystream library will print debug output if DEBUG is defined at all, even if it is DEBUG=false. So we just unconditionally clear the variable in the module.
=> fix: don't spew junk to stdout if environment variable DEBUG is defined

README.md
This is part of Lagoon releases now.
=> chore: remove "experimental" from the README

go.mod, go.sum, internal/keycloak/client.go, internal/keycloak/userattributes.go, internal/keycloak/userattributes_test.go
* Previously we were using https://github.com/square/go-jose/tree/v2 which hasn't seen an update in over a year and may be unmaintained? In any case, https://github.com/golang-jwt/jwt seems to be more widely used and better maintained. So switch to that library. This also allowed improving the structure of the claims unmarshalling logic.
* I also took the opportunity to increase the rigour of token validation slightly by checking the `azp` claim.
=> feat: switch JWT library

internal/keycloak/client.go
The signing algorithm is checked against the provided key, so there should not be any possibility of falling victim to `alg: none`, but check manually too just to be sure.
=> feat: validate the JWT signing algorithm manually

internal/sshportalapi/sshportal.go, internal/sshserver/authhandler.go, internal/sshserver/sessionhandler.go, internal/sshtoken/authhandler.go, internal/sshtoken/sessionhandler.go
These metrics are never presented in a real service but they are built together when generating coverage reports.
This would be a breaking change if ssh-portal was part of any Lagoon release.
=> feat: rename metrics to avoid duplicate names

internal/keycloak/useraccesstoken.go, internal/sshtoken/sessionhandler.go
This command returns the entire access token response as opposed to "token", which returns just the access token.
See https://www.rfc-editor.org/rfc/rfc6749#section-4.1.4 for details
=> feat: add support in ssh-token for "grant" command

internal/k8s/exec.go, internal/sshserver/sessionhandler.go
SSH always wraps commands in a shell before executing them.
=> fix: wrap all commands in a shell

cmd/ssh-token/serve.go, internal/lagoondb/client.go, internal/sshportalapi/sshportal.go, internal/sshserver/sessionhandler.go, internal/sshtoken/authhandler.go, internal/sshtoken/serve.go, internal/sshtoken/sessionhandler.go
Update the `ssh-token` service to return a more helpful error message to a user who attempts to get a shell into a Lagoon environment through the `ssh-token` service. The error message now contains the ssh-portal endpoint that  the user should be using instead.
The ssh-portal endpoint message is only returned if the user actually has permission to access that environment. Otherwise a generic error is returned. This is designed to avoid leaking information about valid environment names.
Closes: #139
=> Return ssh-portal endpoint on attempted shell access through ssh-token service

internal/lagoondb/client.go
The query to check if an environment exists currently returns the first matching environment, which could or could not be a deleted environment, in this case, removing the `limit 1` reveals the second environment
```
MariaDB [infrastructure]> SELECT
->     environment.environment_type AS type,
->     environment.id AS id,
->     environment.name AS name,
-> environment.openshift_project_name AS namespace_name,
->     project.id AS project_id,
-> project.name AS project_name
-> FROM environment JOIN project ON environment.project = project.id
-> WHERE environment.openshift_project_name = 'as-demo-test1-master-alt-test1'
-> LIMIT 1;
+-------------+------+------------------+--------------------------------+------------+---------------+
| type        | id   | name             | namespace_name …
```
=> fix: exclude deleted environments

cmd/ssh-portal/main.go, cmd/ssh-portal/serve.go, go.mod, go.sum, internal/k8s/client.go, internal/k8s/finddeployment.go, internal/k8s/logs.go, internal/sshserver/connectionparams.go, internal/sshserver/connectionparams_test.go, internal/sshserver/helper_test.go, internal/sshserver/serve.go, internal/sshserver/sessionhandler.go
This feature allows users who can ssh into a pod to instead gather container logs from the pod to be returned via the SSH connection.
Features:
* Select `service`, and optionally `container` to retrieve logs from.
* Select number of log lines to return.
* Optionally stream logs live from the service (i.e. "follow").
* Select all pods in a service and seamlessly handle scaling up/down (pods being added/removed from service).
* Timestamp and pod/container prefix on all log lines, with format matching `kubectl log`.
How to use:
```bash
ssh $PROJECT-$ENVIRONMENT@$SSH_PORTAL_HOSTNAME service=$SERVICE [container=$CONTAINER] logs=tailLines=$LINES[,follow]
```
This feature is disabled by default. Enable it via the `LOG_ACCESS_ENABLED=true` environment variable, or by the `--log-access-enabled` …
=> Implement log fetching

.gitignore
The make cover target generates this file while calculating coverage.
=> chore: add cover.out to gitignore

cmd/ssh-portal-api/serve.go, cmd/ssh-token/serve.go, go.mod, internal/keycloak/client.go, internal/keycloak/jwt_test.go, internal/keycloak/useraccesstoken.go, internal/keycloak/userrolesandgroups.go
This change adds a rate limit to the Keycloak client implemented in SSH Portal.
The default rate limit is 10 requests per second, but can be configured via an environment variable.
Documentation will be added in a follow-up PR.
=> feat: rate limit keycloak API access

.goreleaser.yaml, Dockerfile
Previous changes broke docker images and also remove the v prefix from the image version tag . This change adds the prefix back and makes the docker images work again.
=> fix: unbreak images

cmd/ssh-portal-api/serve.go, cmd/ssh-portal/serve.go, cmd/ssh-token/serve.go, internal/metrics/metrics.go, internal/sshtoken/authhandler.go
This change cleanly handles multiple goroutines and ensure all errors
are handled.
=> fix: refactor goroutine handling

go.mod, internal/k8s/logs.go
Go 1.22 brings changes to the way loop iteration works with inner
closures. So take advantage of this feature to remove redundancy.
https://go.dev/blog/loopvar-preview
=> feat: upgrade module to Go 1.22

.github/workflows/release.yaml, .gitignore, .goreleaser.yaml
This change replaces Snyk SBOM generation with Github because the latter
is more detailed.
=> fix: switch to simple SBOM generation

.github/dependabot.yaml
* change the dependabot version update interval to monthly
* only group patch and minor version updates.
major versions get their own PR for ease of tracking changes.
=> chore: update dependabot configuration

.github/dependabot.yaml
This is required for the commitlint action.
=> chore: enforce dependabot scope on commits

go.mod
Ensure the version number is compatible with the go.mod version
standard. This fixes a problem with CodeQL scans in the CI system.
https://go.dev/doc/toolchain#version
=> chore: bump go version number in go.mod

cmd/ssh-portal/serve.go, internal/sshserver/serve.go
Implements https://github.com/uselagoon/lagoon/issues/3693 for ssh-portal.
=> feat: add option for login banner on ssh-portal

go.mod, go.sum, internal/lagoondb/client.go, internal/lagoondb/client_test.go, internal/lagoondb/helper_test.go, internal/sshportalapi/server.go, internal/sshportalapi/sshportal.go, internal/sshtoken/authhandler.go, internal/sshtoken/serve.go
Update the `last_used` attribute of ssh keys using the same technique as https://github.com/uselagoon/lagoon/pull/3675:
* Convert time to a string to be parsed by MySQL to `DATETIME` column type.
* Use UTC timezone.
=> Update last used timestamp on ssh keys when used

internal/keycloak/groups.go
Previously, group data retrieved from in-memory cache was counted
towards the keycloak API rate limit.
With this change, data retrieved from cache does not count towards the
rate limit because the cache does not actually hit the keycloak API.
=> fix: avoid spurious rate limit

internal/bus/ssh.go, internal/sshportalapi/server.go, internal/sshportalapi/sshportal.go, internal/sshserver/authhandler.go, internal/sshserver/serve.go, internal/sshtoken/serve.go
This change fixes a bug where ssh-portal binaries were unnecessarily
exposing ssh-portal-api related metrics (these metrics are always zero
in ssh-portal).
Previously ssh-portal's sshserver package was importing sshportalapi
(and thus getting the unnecessary metrics) just for the bus message
struct definitions.
By moving the message struct definitions out into their own package,
both sshserver and sshportalapi can import the message definitions as
required without any side effects (such as metrics registrations).
=> fix: move NATS message definitions into separate package

README.md, cmd/keycloak-debug/dumpgroups.go, cmd/keycloak-debug/main.go, go.mod
This command is intended to be use for development/debugging.
See the README for instructions.
=> Add command to help debug Keycloak group permissions

cmd/ssh-portal/serve.go, internal/sshportalapi/server.go, internal/sshportalapi/sshportal.go, internal/sshportalapi/sshportal_test.go, internal/sshserver/authhandler.go, internal/sshserver/serve.go
Manually marshal JSON as per [recommendation from upstream](https://github.com/nats-io/nats-architecture-and-design/issues/291#issuecomment-2308956398).
=> feat: avoid deprecated NATS API

go.mod, go.sum, internal/k8s/client.go, internal/k8s/exec.go, internal/k8s/exec_test.go
The idle labels and annotations can now have the lagoon.sh suffix as
amazee.io.
This change adds support for both suffixes, with idling.lagoon.sh taking
priority over idling.amazee.io.
Closes: #458
=> feat: support the new idle labels and annotations

cmd/ssh-portal/serve.go, internal/k8s/client.go, internal/k8s/exec_test.go, internal/k8s/logs.go, internal/k8s/logs_test.go, internal/sshserver/sessionhandler.go
* limit logs session concurrency (default 32 maximum)
* limit logs streaming time (default 4h maximum)
* export more metrics related to logs sessions
=> Add limits to logs sessions

go.mod, go.sum, internal/sshserver/sessionhandler.go, internal/sshserver/sessionhandler_test.go
Previously, complex shell commands were not escaped correctly which led to ssh commands like:
```shell
ssh example-master@ssh.test6.amazee.io /bin/sh -c '( echo foo; echo bar; echo baz ) | tail -n2'
```
Returning an error like:
```
sh: syntax error: unexpected "("
```
This change implements shell escaping using the algorithm described in ponit 1. of [this stack overflow answer](https://stackoverflow.com/a/20053121) to correctly handle complex ssh commands such as the one above.
=> Correctly escape complex shell commands

cmd/keycloak-debug/dumpgroups.go, cmd/ssh-portal-api/serve.go, cmd/ssh-token/serve.go, internal/keycloak/ancestorgroups_test.go, internal/keycloak/client.go, internal/keycloak/jwt_test.go, internal/keycloak/usergroups_test.go
Support for https://github.com/uselagoon/lagoon/pull/3860 and the enforcement of TLS for local development. There needs to be a way to have the ssh-portal ignore certificates if required.
=> feat: support insecure tls connections if required

.goreleaser.yaml, Makefile, README.md, cmd/ssh-portal-api/version.go, cmd/ssh-portal/version.go, cmd/ssh-token/version.go
* update the `build` Makefile target to actually work with GoReleaser 2.
* add a `release-snapshot` target to also build multiarch binaries and docker images.
* document these targets in the README.
=> Improve local development experience

internal/k8s/exec.go, internal/k8s/exec_test.go
Ignore pods which are not in running state during the exec process.
Closes: #537
=> Skip succeeded pods
